# Define UI for application that draws a histogram
ui <- fluidPage(
  
  # Application title
  titlePanel("Sticker profitability"),

  # Sidebar with a slider input for number of bins 
  sidebarLayout(
    sidebarPanel(
      sliderInput("PricePoint",
                  "Price Point:",
                  min = 1,
                  max = 50,
                  value = 12),
      sliderInput("PrinterCost",
                  "Price of printer:",
                  min = 0,
                  max = 10000,
                  value = 2300,
                  step = 100),
      sliderInput("CutterCost",
                  "Cost of Cutter:",
                  min = 0,
                  max = 10000,
                  value = 1900,
                  step = 100),
      sliderInput("LaminatorCost",
                  "Cost of Laminator:",
                  min = 0,
                  max = 10000,
                  value = 200,
                  step = 100),
      sliderInput("LaminatorRollCost",
                  "Cost of Laminator Roll:",
                  min = 0,
                  max = 200,
                  value = 90,
                  step = 10),
      sliderInput("LengthOfLamnatorRollFeet",
                  "Length of Laminator roll (feet):",
                  min = 10,
                  max = 200,
                  value = 90),
      sliderInput("LaminatorSheetMarginInch",
                  "Size of Laminator header/foot margin (inches):",
                  min = 0,
                  max = 10,
                  value = 1),
      sliderInput("UnitsPerInkCartridge",
                  "Orders per ink cartridge:",
                  min = 100,
                  max = 5000,
                  value = 1200,
                  step = 100),
      sliderInput("NumberOfInkCartridges",
                  "Count of ink cartridges in printer:",
                  min = 1,
                  max = 12,
                  value = 11,
                  step = 1),
      sliderInput("PriceOfInkCartridge",
                  "Price of each ink cartridge:",
                  min = 50,
                  max = 400,
                  value = 320,
                  step = 10),
      sliderInput("LengthOfPaperRollFeet",
                  "Length of paper roll (feet):",
                  min = 10,
                  max = 200,
                  value = 30,
                  step = 10),
      sliderInput("PriceOfPaper",
                  "Price of paper roll:",
                  min = 10,
                  max = 400,
                  value = 200,
                  step = 10),
      sliderInput("LengthPerOrderInches",
                  "Length of paper used per order (inches):",
                  min = 1,
                  max = 50,
                  value = 16),
      sliderInput("StorefrontTransactionPercentage",
                  "Percent of sale to the storefront:",
                  min = 1,
                  max = 20,
                  value = 6.5,
                  step = .1)
    ),
    
    # Show a plot of the generated distribution
    mainPanel(
      plotOutput("pricePlot")
    )
  )
)
